### ISSUE TITLE
Read from Wallet RPC times out after a few requests when dealing with multiple wallets

### ISSUE THREAD

**Issue by chwykim** [monero-ecosystem/monero-python#52] opened 2019-06-08 23:36 UTC
I wrote a program that repeatedly requests for JSON responses from Monero Wallet RPCs at time intervals ranging from 10 seconds to a minute. Everything is running on a testnet in my local network.

Strangely, the RPC often stops responding after a while, causing a time out error. I cannot even reconnect to the wallet once the error occurs.

I observed that the problem only occurs when I run multiple instances of the program at the same time. So perhaps there is some kind of collision happening. Each instance of the program is connected to a different wallet on a different port, though. Also, the problem persists when I run a single Python module connected to multiple wallets.

The following is the traceback output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 307, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=28023): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/econ_reader.py", line 31, in <module>
    tx = w.transfer(D[row['dest_addr']], Decimal(row['xmr_amount']))
  File "/usr/local/lib/python3.6/dist-packages/monero/wallet.py", line 259, in transfer
    relay=relay)
  File "/usr/local/lib/python3.6/dist-packages/monero/account.py", line 97, in transfer
    relay=relay)
  File "/usr/local/lib/python3.6/dist-packages/monero/backends/jsonrpc.py", line 307, in transfer
    _transfers = self.raw_request('transfer_split', data)
  File "/usr/local/lib/python3.6/dist-packages/monero/backends/jsonrpc.py", line 324, in raw_request
    self.url, headers=hdr, data=json.dumps(data), auth=auth, timeout=self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=28023): Read time
```

**Comment by emesik** [comment] 2019-06-08 23:46
Perhaps try running `monero-wallet-rpc --log-level 4` and watch if those failed connection attempts are reported by log messages in any way.

Can you describe your environment a bit?

- Are those RPCs running for long time or just launched for a moment and shut down afterwards?
- Are you sure they aren't refreshing the wallet after longer inactivity when those errors occur?
- Do they connect to the daemon and is the daemon running well?

**Comment by chwykim** [comment] 2019-06-09 00:01
Thanks for the quick reply. When I launch three RPCs and run a Python module that calls transactions from them, everything runs fine for a few minutes, taking perhaps around 10 requests. But eventually, two of the RPCs stop responding to requests from the Python module, and only one remains responsive. All of the RPCs continue running, though. It's just that the requests time out.

**Comment by chwykim** [comment] 2019-06-09 18:11
The following log output may be relevant?
```
2019-06-09 14:10:13.141 T READ ENDS: Success. bytes_tr: 169
2019-06-09 14:10:13.141 T http_stream_filter::parse_cached_header(*)
2019-06-09 14:10:13.141 T READ ENDS: Success. bytes_tr: 505
2019-06-09 14:10:13.142 D Block is already in blockchain: 293ecc335f8b4cd5c97e914fdd4c58fbb4cc30dee98439bc14c0674e51dca537
2019-06-09 14:10:13.142 T update_pool_state start
2019-06-09 14:10:13.142 T READ ENDS: Success. bytes_tr: 159
2019-06-09 14:10:13.142 T http_stream_filter::parse_cached_header(*)
2019-06-09 14:10:13.142 T READ ENDS: Success. bytes_tr: 45
2019-06-09 14:10:13.142 T update_pool_state got pool
2019-06-09 14:10:13.142 T update_pool_state done first loop
2019-06-09 14:10:13.142 T update_pool_state done second loop
2019-06-09 14:10:13.142 T update_pool_state end
2019-06-09 14:10:13.142 I Refresh done, blocks received: 16, balance (all accounts): 1126.045506445534, unlocked: 756.657344355871
^C2019-06-09 14:10:13.453       D JOINING all threads - almost
2019-06-09 14:10:13.453 D JOINING all threads - DONE
2019-06-09 14:10:13.453 I net_service loop stopped.
2019-06-09 14:10:13.453 W Stopped wallet RPC server
2019-06-09 14:10:13.453 W Saving wallet...
2019-06-09 14:10:13.453 D trimming to 0, offset 0
2019-06-09 14:10:13.473 D Problems at ssl shutdown: uninitialized
2019-06-09 14:10:13.473 D Problems at cancel: Bad file descriptor
2019-06-09 14:10:13.473 D Problems at shutdown: Bad file descriptor
2019-06-09 14:10:13.475 W Successfully saved
2019-06-09 14:10:13.475 T [sock -1] Socket destroyed without shutdown.
2019-06-09 14:10:13.475 T [sock -1] Socket destroyed
2019-06-09 14:10:13.475 D Destructing connection #3 to 0.0.0.0
```

**Comment by emesik** [comment] 2019-06-11 12:16
It seems to me that the problem is present in `monero-wallet-rpc` itself, perhaps in the part that handles mempool transactions. Try submitting it to [monero-project](https://github.com/monero-project/monero) itself. Please make sure to include the version you use and detailed logs.

You may also try to connect to unresponsive RPC by `curl` or `wget` request. If that times out too, we're sure the RPC wallet is broken. If it succeeds, the problem could be on Python side, but ATM I have no slightest idea where it could be.

**Comment by chwykim** [comment] 2019-06-11 14:54
Thanks for your help. I remember trying curl and usually being timed out. I posted the issue here: https://github.com/monero-project/monero/issues/5612

**Comment by emesik** [comment] 2019-07-19 09:06
I'm closing it because it's not related to this project. If you think otherwise, feel free to reopen and elaborate. Thanks!

**Closed by emesik** 2019-07-19 09:06 UTC
